# This file is generated by scripts/update-formula.sh.
class Donsetch < Formula
  desc "Web fetch, search and crawl for AI agents: stealthy, keyless, token-efficient MCP server"
  homepage "https://github.com/dondai44423/donsetch"
  version "4.4.3"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dondai44423/donsetch/releases/download/v4.4.3/donsetch-darwin-x64.tar.gz"
      sha256 "e934bf8df8fab957a9be8659d08ec188f517d93dc9dc02cd5d346bab11501e1a"
    else
      url "https://github.com/dondai44423/donsetch/releases/download/v4.4.3/donsetch-darwin-arm64.tar.gz"
      sha256 "32f20250654532b9b280d07be9c4c4ad96e3da5f8db6d413f3e3f39c9d430fd6"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dondai44423/donsetch/releases/download/v4.4.3/donsetch-linux-x64.tar.gz"
      sha256 "145e57048d1dfeb42aa683bd8ca67d11b6398f5259d3bb50c6a676a19ff2ea64"
    else
      url "https://github.com/dondai44423/donsetch/releases/download/v4.4.3/donsetch-linux-arm64.tar.gz"
      sha256 "9c315fa0ffc8eb21188c44bc71af0b630216d68879cb776b2a6bea5f60b61b6e"
    end
  end

  def install
    bin.install "donsetch"
    # ONNX Runtime is dlopen'd from beside the binary (Linux .so,
    # macOS .dylib since v4.3.6); absent on targets built without
    # ocr/rerank, so both installs are conditional.
    if OS.mac?
      bin.install "libonnxruntime.dylib" if File.exist?("libonnxruntime.dylib")
    else
      bin.install "libonnxruntime.so" if File.exist?("libonnxruntime.so")
    end
  end

  def caveats
    <<~EOS
      DonSeTch is an MCP server: connect from your MCP client via
        donsetch mcp
      Run `donsetch doctor` to verify the install.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/donsetch --version")
  end
end
