# This file is generated by scripts/update-formula.sh.
class Donsetch < Formula
  desc "Web fetch, search and crawl for AI agents: stealthy, keyless, token-efficient MCP server"
  homepage "https://github.com/dondai44423/donsetch"
  version "4.1.1"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dondai44423/donsetch/releases/download/v4.1.1/donsetch-darwin-x64.tar.gz"
      sha256 "8b10eb3654c005703ceee0dc98ca41b141560987eb3e2ce4f6ea08d6b31fe216"
    else
      url "https://github.com/dondai44423/donsetch/releases/download/v4.1.1/donsetch-darwin-arm64.tar.gz"
      sha256 "8cf5700e4ef05ab05bc01957c677ab81d78cc4fe3eec1a6fb803b4717e74ad1f"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dondai44423/donsetch/releases/download/v4.1.1/donsetch-linux-x64.tar.gz"
      sha256 "844592c8ce19231582999ec390547e6cea488481c788719fc994592177cebae9"
    else
      url "https://github.com/dondai44423/donsetch/releases/download/v4.1.1/donsetch-linux-arm64.tar.gz"
      sha256 "e34e5155275c86e6678d5391e6c2c8f1ac4f54aa0e8d024fea387d6dc3c6927e"
    end
  end

  def install
    bin.install "donsetch"
  end

  def caveats
    <<~EOS
      DonSeTch is an MCP server: connect from your MCP client via
        donsetch mcp
      Run `donsetch doctor` to verify the install.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/donsetch --version")
  end
end
