# This file is generated by scripts/update-formula.sh.
class Donsetch < Formula
  desc "Web fetch, search and crawl for AI agents: stealthy, keyless, token-efficient MCP server"
  homepage "https://github.com/dondai44423/donsetch"
  version "4.4.2"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dondai44423/donsetch/releases/download/v4.4.2/donsetch-darwin-x64.tar.gz"
      sha256 "c952044ad17c5f60b30af72413f552f25c74e1541043485336fae6a2d65c1862"
    else
      url "https://github.com/dondai44423/donsetch/releases/download/v4.4.2/donsetch-darwin-arm64.tar.gz"
      sha256 "ce910cc20e22b5e620b4d2f50eed9cc284a56bd7adbba410136250217ed5fe14"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dondai44423/donsetch/releases/download/v4.4.2/donsetch-linux-x64.tar.gz"
      sha256 "be4813d0da332a2c46dddfab42b04a7cbc162b3edc49f3a87442168f84439739"
    else
      url "https://github.com/dondai44423/donsetch/releases/download/v4.4.2/donsetch-linux-arm64.tar.gz"
      sha256 "a50495c4474629a55e1fb4b4556503db49d698f41499c1c03c95e71f8a95d88b"
    end
  end

  def install
    bin.install "donsetch"
    # ONNX Runtime is dlopen'd from beside the binary (Linux .so,
    # macOS .dylib since v4.3.6); absent on targets built without
    # ocr/rerank, so both installs are conditional.
    if OS.mac?
      bin.install "libonnxruntime.dylib" if File.exist?("libonnxruntime.dylib")
    else
      bin.install "libonnxruntime.so" if File.exist?("libonnxruntime.so")
    end
  end

  def caveats
    <<~EOS
      DonSeTch is an MCP server: connect from your MCP client via
        donsetch mcp
      Run `donsetch doctor` to verify the install.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/donsetch --version")
  end
end
