#!/usr/bin/env bash
set -euo pipefail

repo="dondai44423/donsetch"
tag="${1:-}"

if [[ -z "$tag" ]]; then
  tag="$(curl -fsSL "https://api.github.com/repos/${repo}/releases/latest" \
    | python3 -c 'import json, sys; print(json.load(sys.stdin)["tag_name"])')"
fi

if [[ ! "$tag" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "invalid release tag: $tag" >&2
  exit 1
fi

version="${tag#v}"
if grep -Eq "^[[:space:]]*version \"${version}\"[[:space:]]*$" Formula/donsetch.rb; then
  echo "already at ${version}"
  exit 0
fi

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

declare -A hashes
for platform in darwin-x64 darwin-arm64 linux-x64 linux-arm64; do
  asset="donsetch-${platform}.tar.gz"
  checksum_url="https://github.com/${repo}/releases/download/${tag}/${asset}.sha256"
  checksum_file="${tmp_dir}/${platform}.sha256"
  curl -fsSL "$checksum_url" -o "$checksum_file"
  hash="$(awk 'NF { print $1; exit }' "$checksum_file")"
  if [[ ! "$hash" =~ ^[[:xdigit:]]{64}$ ]]; then
    echo "invalid SHA-256 sidecar for ${asset}" >&2
    exit 1
  fi
  hashes["$platform"]="$(printf '%s' "$hash" | tr '[:upper:]' '[:lower:]')"
done

cat > Formula/donsetch.rb <<'EOF'
# This file is generated by scripts/update-formula.sh.
class Donsetch < Formula
  desc "Web fetch, search and crawl for AI agents: stealthy, keyless, token-efficient MCP server"
  homepage "https://github.com/dondai44423/donsetch"
  version "__VERSION__"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dondai44423/donsetch/releases/download/__TAG__/donsetch-darwin-x64.tar.gz"
      sha256 "__DARWIN_X64__"
    else
      url "https://github.com/dondai44423/donsetch/releases/download/__TAG__/donsetch-darwin-arm64.tar.gz"
      sha256 "__DARWIN_ARM64__"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dondai44423/donsetch/releases/download/__TAG__/donsetch-linux-x64.tar.gz"
      sha256 "__LINUX_X64__"
    else
      url "https://github.com/dondai44423/donsetch/releases/download/__TAG__/donsetch-linux-arm64.tar.gz"
      sha256 "__LINUX_ARM64__"
    end
  end

  def install
    bin.install "donsetch"
  end

  def caveats
    <<~EOS
      DonSeTch is an MCP server: connect from your MCP client via
        donsetch mcp
      Run `donsetch doctor` to verify the install.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/donsetch --version")
  end
end
EOF

sed -i \
  -e "s/__VERSION__/${version}/g" \
  -e "s/__TAG__/${tag}/g" \
  -e "s/__DARWIN_X64__/${hashes["darwin-x64"]}/g" \
  -e "s/__DARWIN_ARM64__/${hashes["darwin-arm64"]}/g" \
  -e "s/__LINUX_X64__/${hashes["linux-x64"]}/g" \
  -e "s/__LINUX_ARM64__/${hashes["linux-arm64"]}/g" \
  Formula/donsetch.rb
